name: Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.vscode/**'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:coverage

      - name: Upload coverage
        uses: coverallsapp/github-action@v2

      - name: Create release tag
        id: tag
        run: echo "release_tag=$(date +"%Y.%-m.%-d.%-H%-M")" >> $GITHUB_OUTPUT

      - name: Write release tag to files
        run: |
          echo Writing release tag to package.json
          jq '.version |= "${{ steps.tag.outputs.release_tag }}"' package.json | tee tmp-package.json && mv tmp-package.json package.json
          echo Writing release tag to public/manifest.json
          jq '.version |= "${{ steps.tag.outputs.release_tag }}"' public/manifest.json | tee public/tmp-manifest.json && mv public/tmp-manifest.json public/manifest.json

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: aws-sso-account-filter-web-extension-v${{ steps.tag.outputs.release_tag }}
          path: dist/
          retention-days: 90
          if-no-files-found: error

      - name: Setup Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit ammended files with release tag
        run: |
          git status
          git commit --all --message "🤖 Release v${{ steps.tag.outputs.release_tag }}"
          git push

      - name: Compress dist for release
        run: |
          cd dist
          zip -r ../aws-sso-account-filter-web-extension-v${{ steps.tag.outputs.release_tag }}.zip .

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.tag.outputs.release_tag }}
          files: aws-sso-account-filter-web-extension-v${{ steps.tag.outputs.release_tag }}.zip
          generate_release_notes: true
