name: Main

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:coverage

      - name: Upload coverage
        uses: coverallsapp/github-action@v2

      - name: Build
        run: npm run build

      - name: Create release tag
        run: echo "release_tag=v$(date + "%Y.%m.%d%H%M")" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: aws-sso-account-filter-web-extension-${{ steps.tag.outputs.release_tag }}
          path: dist/
          retention-days: 90
          if-no-files-found: error

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: dist/
          generate_release_notes: true
