name: Pull request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Volta Node Version
        id: volta_version
        run: echo "node_version=$(jq -r .volta.node package.json)" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.volta_version.outputs.node_version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:coverage

      - name: Upload coverage
        uses: coverallsapp/github-action@v2

      - name: Build
        run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: aws-sso-account-filter-web-extension-${{ github.run_id }}
          path: dist/
          retention-days: 14
          if-no-files-found: error
