name: Pull request

env:
  EXTENSION_FILE_NAME: aws-sso-account-filter-web-extension

on: pull_request

jobs:
  build:
    name: Build
    timeout-minutes: 3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test:coverage

      - name: Build
        run: pnpm run build

      - name: Create Chrome dist directory
        run: |
          cp -r  ./dist/ ./chrome-dist/
          cd chrome-dist
          cat manifest.json | jq 'del(.browser_specific_settings)' > chrome-manifest.json && mv chrome-manifest.json manifest.json

      - name: Create Firefox dist directory
        run: cp -r  ./dist/ ./firefox-dist/

      - name: Upload Chrome artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-${{ env.EXTENSION_FILE_NAME }}-${{ github.run_id }}
          path: chrome-dist/
          retention-days: 7
          if-no-files-found: error

      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-${{ env.EXTENSION_FILE_NAME }}-${{ github.run_id }}
          path: firefox-dist/
          retention-days: 7
          if-no-files-found: error
