name: Pull request

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create release tag
        id: tag
        run: echo "release_tag=$(date +"%Y.%m.%d%H%M")" >> $GITHUB_OUTPUT

      - name: Write release tag to files
        run: |
          echo Writing release tag to package.json
          cat package.json | jq '.version |= "${{ steps.tag.outputs.release_tag }}"' | tee package.json >/dev/null
          echo Writing release tag to public/manifest.json
          cat public/manifest.json | jq '.version |= "${{ steps.tag.outputs.release_tag }}"' | tee public/manifest.json >/dev/null

      - name: Debug
        run: |
          echo package.json
          cat package.json
          echo public/manifest.json
          cat public/manifest.json

        # - uses: actions/checkout@v3

        # - name: Setup Node.js
        #   uses: actions/setup-node@v3
        #   with:
        #     node-version: 18.x
        #     cache: 'npm'

        # - name: Install dependencies
        #   run: npm ci

        # - name: Lint
        #   run: npm run lint

        # - name: Test
        #   run: npm run test:coverage

        # - name: Upload coverage
        #   uses: coverallsapp/github-action@v2

        # - name: Build
        #   run: npm run build

        # - uses: actions/upload-artifact@v3
        #   with:
        #     name: aws-sso-account-filter-web-extension-${{ github.run_id }}
        #     path: dist/
        #     retention-days: 14
        #     if-no-files-found: error
